name: BlogComment
on:
  issues:
    types:
      - opened

jobs:
  blog:
    name: BlogComment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Issue Content
        id: issue-content
        run: |
          issue_content=$(echo "${{ github.event.issue.title }}" | tr -d '\n' | tr -d '\r' | tr -d '\t')
          if [[ "$issue_content" == *"Add Github Project"* ]]; then
            echo "::set-output name=add_text::true"
          else
            echo "::set-output name=add_text::false"
          fi
      - name: Update Gayhub.md
        if: steps.issue-content.outputs.add_text == 'true'
        run: |
          cd /home/runner/work/Wiki/Wiki/
          echo "${{ github.event.issue.body }}" >> ./docs/docs/other/gayhub.md
      - name: Change Working Directory
        run: cd /home/runner/work/Wiki/Wiki/  # 更改为您想要执行命令的目录路径
      - name: Commit files
        if: steps.issue-content.outputs.add_text == 'true'
        id: commit-files
        run: |
          if [ -n "$(git status --porcelain ./docs/docs/other/gayhub.md)" ]; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add -A
            git commit -m "docs: update blog"
            git push
          else
            echo "No changes detected"
          fi
      - name: Close Issue
        if: steps.issue-content.outputs.add_text == 'true'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            })